# fly.toml app configuration file generated for hostelhop on 2023-07-01T11:30:11-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hostelhop"
primary_region = "ams"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
